apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string
  workspaces:
    - name: output
      mountPath: /source
  steps:
    - name: clone
      image: alpine/git
      script: |
        
        git clone $(params.repo-url) /source
